version: 0.2

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  install:
    commands:
      - curl -Ls https://github.com/spf13/hugo/releases/download/v0.30.2/hugo_0.30.2_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz
      - tar xf /tmp/hugo.tar.gz -C /tmp
      - mv /tmp/hugo /usr/bin/hugo
      - rm -rf /tmp/hugo
  build:
    commands:
      - cat buildspec.yml
      - hugo

  post_build:
    commands:
      - aws s3 sync --acl public-read --delete public s3://aws-website-httpsdashbirdio-nvzul --cache-control max-age=3600
      - aws cloudfront create-invalidation --distribution-id E19T4M9Y3XAQXS --paths '/*'

artifacts:
  files:
    - 'public/**/*'
  # discard-paths: yes
