version: 0.2

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  install:
    commands:
      - curl -Ls https://github.com/spf13/hugo/releases/download/v0.30.2/hugo_0.30.2_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz
      - tar xf /tmp/hugo.tar.gz -C /tmp
      - mv /tmp/hugo /usr/bin/hugo
      - rm -rf /tmp/hugo
  build:
    commands:
      - cat buildspec.yml
      - hugo

artifacts:
  files:
    - 'public/**/*'
  discard-paths: yes
