workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master


version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.38
    steps:
      - checkout
      - run:
          name: "Build Website"
          command: hugo
      # - run:
      #     name: "Test Website"
      #     command: htmlproofer public --allow-hash-href --check-html --empty-alt-ignore --disable-external

  deploy:
    docker:
      - image: cibuilds/hugo:0.38
    steps:
      - checkout
      - run:
          name: "Installing aws"
          command: |
            apk add --update python python-dev py-pip build-base
            pip install awscli
      - run:
          name: "Build Website"
          command: hugo
      - run:
          name: "Deploy"
          command: |
            aws s3 sync --acl public-read --sse --delete public/  s3://aws-website-httpsdashbirdio-nvzul
            aws cloudfront create-invalidation --distribution-id E19T4M9Y3XAQXS --paths '/*'

